import * as content from '../api/v1/_game-data.js';
globalThis.MURSAL_CONTENT=content;
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,stat} from 'node:fs/promises';
const {LEVELS,SIGNS,SOURCES,buildQuestions}=await import('../game/data/worlds.js');
const {freshSave,normalizeSave,regenerate,isUnlocked,createRun,answerRun,usePower,nextQuestion,finishRun,REGEN_MS}=await import('../game/engine.js');
function win(id,s){const r=createRun(id,s);for(let i=0;i<r.questions.length;i++){answerRun(r,s,r.questions[r.index].answer);if(i<r.questions.length-1)nextQuestion(r,s);}return finishRun(r,s);}
test('60 levels have valid questions, unique choices, source references and local images',async()=>{assert.equal(LEVELS.length,60);assert.equal(SIGNS.length,27);for(const l of LEVELS){const qs=buildQuestions(l);assert.equal(qs.length,l.count);for(const q of qs){assert.equal(q.options.length,new Set(q.options).size);assert.ok(q.options.includes(q.answer));for(const id of q.sourceIds)assert.ok(SOURCES[id]);}}for(const s of SIGNS)assert.ok((await stat(new URL('../game/'+s.image,import.meta.url))).size>0);});
test('complete campaign unlocks sequentially and awards badge only at level 20',()=>{const s=freshSave();assert.throws(()=>createRun(2,s));for(let id=1;id<=20;id++){assert.ok(isUnlocked(s,id));const result=win(id,s);assert.equal(result.stars,3);assert.equal(s.badge,id===20);}assert.equal(Object.keys(s.levels).length,20);assert.equal(Object.values(s.levels).reduce((n,l)=>n+l.stars,0),60);assert.ok(s.xp>2000);});
test('replaying cannot farm XP, lower result never erases best stars',()=>{const s=freshSave();win(1,s);const before=s.xp;assert.equal(win(1,s).gain,0);assert.equal(s.xp,before);const r=createRun(1,s);r.questions.forEach((q,i)=>{answerRun(r,s,i<3?q.answer:q.options.find(o=>o!==q.answer));if(i<4)nextQuestion(r,s);});const res=finishRun(r,s);assert.equal(res.stars,1);assert.equal(s.levels[1].stars,3);assert.equal(s.xp,before);});
test('shield protects energy, not correctness; bosses forbid powers',()=>{const s=freshSave();const r=createRun(1,s);assert.equal(usePower(r,'shield'),true);assert.equal(usePower(r,'shield'),false);answerRun(r,s,r.questions[0].options.find(o=>o!==r.questions[0].answer));assert.equal(s.energy,5);assert.equal(r.correct,0);assert.equal(r.feedback.protectedError,true);assert.equal(answerRun(r,s,r.questions[0].answer),null);for(let i=1;i<10;i++)win(i,s);const boss=createRun(10,s);for(const power of ['vision','shield','boost'])assert.equal(usePower(boss,power),false);});
test('boost requires correct knowledge and is limited to three correct answers',()=>{const s=freshSave(),r=createRun(1,s);usePower(r,'boost');for(let i=0;i<5;i++){answerRun(r,s,r.questions[r.index].answer);if(i<4)nextQuestion(r,s);}assert.equal(r.earned,160);assert.equal(r.boost,0);});
test('zero energy blocks campaign; ordinary practice does not restore lives',()=>{const s=freshSave();s.energy=0;assert.throws(()=>createRun(1,s));const r=createRun(1,s,{practice:true});for(let i=0;i<3;i++){answerRun(r,s,r.questions[r.index].answer);nextQuestion(r,s);}assert.equal(s.energy,0);const res=finishRun(r,s);assert.equal(res.gain,0);assert.deepEqual(s.levels,{});});
test('wrong answers, timeout and zero-energy result do not unlock next level',()=>{const s=freshSave(),r=createRun(1,s);for(let i=0;i<5;i++){answerRun(r,s,null);if(i<4)nextQuestion(r,s);}assert.equal(s.energy,0);assert.equal(finishRun(r,s).passed,false);assert.equal(isUnlocked(s,2),false);});
test('save reload retains achievements and paused round; corrupt data resets safely',()=>{const s=freshSave();win(1,s);s.active=createRun(2,s);answerRun(s.active,s,s.active.questions[0].answer);const restored=normalizeSave(JSON.parse(JSON.stringify(s)));assert.equal(restored.levels[1].stars,3);assert.equal(restored.active.correct,1);assert.equal(restored.active.feedback.correct,true);assert.equal(normalizeSave({version:99}).xp,0);assert.equal(normalizeSave({version:1,energy:NaN,levels:{20:{stars:3,xp:100}}}).badge,false);});
test('elapsed time cannot bypass the comeback challenge',()=>{const s=freshSave(1000);s.energy=1;regenerate(s,1000+2*REGEN_MS);assert.equal(s.energy,1);regenerate(s,1000+20*REGEN_MS);assert.equal(s.energy,1);});
test('PWA keeps relative scope for /game integration',async()=>{const m=JSON.parse(await readFile(new URL('../game/manifest.webmanifest',import.meta.url),'utf8'));assert.equal(m.scope,'./');assert.equal(m.start_url,'./spelen');assert.equal(m.icons.length,3);const sw=await readFile(new URL('../game/sw.js',import.meta.url),'utf8');assert.match(sw,/mursal-hero-/);assert.doesNotMatch(sw,/caches\.keys\(\).*filter\(k=>k!==CACHE/);});



