/* Pashto is independent of Dari/Farsi. Keys are the original Dutch text.
 * These translations are drafts pending native-speaker content review.
 * Do not mark the paid Pashto product ready from the presence of UI strings.
 */
globalThis.MT_PASHTO = Object.freeze({
  'voorrang': 'د لومړي تېرېدو حق',
  'haaientanden': 'د لومړي تېرېدو حق ورکولو مثلثي نښې',
  'rijstrook': 'د تګ لین',
  'invoegen': 'له نښلېدونکي لین څخه اصلي لین ته ننوتل',
  'uitvoegen': 'له اصلي لین څخه وتونکي لین ته وتل',
  'remweg': 'د بریک نیولو واټن',
  'volgafstand': 'له مخکیني موټر سره واټن',
  'zebrapad': 'د پلي کسانو د اوښتو کرښې',
  'rotonde': 'څلورلارې ته ورته ګردچاپېر لاره',
  'snelweg': 'لویه چټکه لاره',
  'dode hoek': 'په هندارو کې نه لیدل کېدونکې ساحه',
  'richtingaanwijzer': 'د لوري ښودلو څراغ',
  'dimlicht': 'ټیټ څراغ',
  'parkeerverbod': 'پارک کول منع دي',
  'stopverbod': 'درېدل منع دي',
  'voetganger': 'پلی کس',
  'fietser': 'بایسکل چلوونکی',
  'gordel': 'د خوندیتوب کمربند',
  'aquaplaning': 'د ټایر او سړک ترمنځ پر اوبو ښویېدل',
  'inhalen': 'له بل موټر څخه مخکې کېدل',
  'vluchtstrook': 'بیړنی لین',
  'matrixbord': 'برېښنايي ترافیکي تابلو',
  'afrit': 'له لویې لارې وتونکې لاره',
  'stopafstand': 'د بشپړ درېدو واټن',
  'Voertuig & documenten': 'موټر او اسناد',
  'Plaats op de weg': 'پر سړک ځای',
  'Snelheid & afstand': 'سرعت او واټن',
  'Voorrang': 'د لومړي تېرېدو حق',
  'Kruispunten': 'څلورلارې',
  'Bijzondere manoeuvres': 'ځانګړي حرکات',
  'Inhalen': 'له بل موټر څخه مخکې کېدل',
  'Stilstaan & parkeren': 'درېدل او پارک کول',
  'Autoweg & autosnelweg': 'د موټرو لاره او لویه چټکه لاره',
  'Weer & zicht': 'هوا او لید',
  'Licht & signalen': 'څراغونه او اشارې',
  'Kwetsbare weggebruikers': 'د سړک زیان‌منونکي کاروونکي',
  'Alcohol & rijgeschiktheid': 'الکول او د موټر چلولو وړتیا',
  'Lading & aanhanger': 'بار او ټرېلر',
  'Milieu & noodsituaties': 'چاپېریال او بیړني حالتونه',
  'Alle': 'ټول', 'Verbod': 'منع', 'Gebod': 'الزام',
  'Waarschuwing': 'خبرداری', 'Informatie': 'معلومات',
  'Voorrangsweg': 'د لومړي تېرېدو حق لرونکې لاره',
  'Je rijdt op een voorrangsweg. Het bord geldt tot bord B2 of een andere duidelijke beëindiging.': 'تاسو د لومړي تېرېدو حق لرونکې لار کې ځئ. دا نښه تر B2 نښې یا بل څرګند پای پورې اعتبار لري.',
  'Einde voorrangsweg': 'د لومړي تېرېدو حق لرونکې لارې پای',
  'Vanaf dit bord is de weg niet langer een voorrangsweg.': 'له دې نښې وروسته دا لاره نور د لومړي تېرېدو حق لرونکې لاره نه ده.',
  'Verleen voorrang aan bestuurders op de kruisende weg': 'د پرېکوونکې لارې چلوونکو ته د لومړي تېرېدو حق ورکړئ',
  'Je moet bestuurders op de kruisende weg voor laten gaan.': 'باید د پرېکوونکې لارې چلوونکي لومړی تېرېدو ته پرېږدئ.',
  'Stop en verleen voorrang': 'ودرېږئ او د لومړي تېرېدو حق ورکړئ',
  'Stop volledig en verleen daarna voorrang aan bestuurders op de kruisende weg.': 'په بشپړ ډول ودرېږئ او بیا د پرېکوونکې لارې چلوونکو ته د لومړي تېرېدو حق ورکړئ.',
  'Maximumsnelheid 50 km/u': 'تر ټولو لوړ سرعت په ساعت کې ۵۰ کیلومتره',
  'Je mag niet sneller rijden dan 50 km/u.': 'تاسو له ۵۰ کیلومتره په ساعت کې چټک تګ نه شئ کولای.',
  'Eenrichtingsweg, gesloten in deze richting': 'یوطرفه لاره؛ له دې لوري ننوتل منع دي',
  'Je mag deze weg vanaf deze kant niet inrijden.': 'له دې خوا دې لارې ته نه شئ ننوتلای.',
  'Gebod rechtdoor te rijden': 'نېغ تګ لازمي دی',
  'Je moet de richting van de pijl volgen: rechtdoor.': 'باید د غشي په لوري، یعنې نېغ، لاړ شئ.',
  'Gevaar': 'خطر',
  'Waarschuwing voor een gevaar waarvoor geen afzonderlijk symbool bestaat.': 'د داسې خطر خبرداری چې ځانګړې نښه نه لري.',
  'Rotonde, verplichte rijrichting': 'ګردچاپېر لاره؛ ټاکلی لوری لازمي دی',
  'Volg de aangegeven rijrichting op de rotonde.': 'په ګردچاپېر لاره کې په ښودل شوي لوري لاړ شئ.',
  'Voetgangersoversteekplaats': 'د پلي کسانو د اوښتو ځای',
  'Let op voetgangers die oversteken of willen oversteken.': 'هغو پلي کسانو ته پام وکړئ چې اوړي یا اوښتل غواړي.',
  'Parkeergelegenheid': 'د پارک کولو ځای',
  'Hier is parkeren toegestaan volgens de plaatselijke voorwaarden.': 'دلته د ځایي شرایطو له مخې پارک کول اجازه لري.',
  'Parkeerverbod': 'پارک کول منع دي',
  'Aan deze zijde van de weg mag je niet parkeren.': 'د سړک پر دې غاړه پارک نه شئ کولای.',
  'Autosnelweg': 'لویه چټکه لاره',
  'Vanaf dit bord gelden de regels voor autosnelwegen.': 'له دې نښې وروسته د لویو چټکو لارو مقررات پلي کېږي.',
  'Een kind staat vlak bij de rijbaan en kijkt naar de overkant.': 'یو ماشوم د سړک د موټرو برخې ته نږدې ولاړ دی او بلې غاړې ته ګوري.',
  'Remmen: een kind kan plotseling de rijbaan oplopen.': 'بریک ونیسئ: ماشوم ښايي ناڅاپه سړک ته راووځي.',
  'Je ziet ruim vooruit een rood verkeerslicht en er rijdt niemand direct achter je.': 'لرې مخکې سور ترافیکي څراغ وینئ او سمدستي شاته مو څوک نه روان دي.',
  'Gas los: je kunt rustig snelheid verminderen en verder vooruit kijken.': 'ګاز پرېږدئ: په ارامۍ سرعت کمولای او مخکې کتلای شئ.',
  'De weg is vrij, je rijdt met veilige snelheid en er is geen direct gevaar.': 'لاره خالي ده، په خوندي سرعت روان یاست او سمدستي خطر نشته.',
  'Niets doen: blijf kijken en houd je snelheid stabiel.': 'هېڅ مه کوئ: کتلو ته دوام ورکړئ او سرعت ثابت وساتئ.',
  'De auto voor je remt plotseling hard.': 'مخکینی موټر ناڅاپه سخت بریک نیسي.',
  'Remmen: het gevaar is direct en de afstand wordt snel kleiner.': 'بریک ونیسئ: خطر سمدستي دی او واټن په چټکۍ کمېږي.',
  'Je nadert een drukke rotonde en ziet verkeer op de rotonde.': 'ګڼې ګردچاپېر لارې ته نږدې کېږئ او پر هغې ترافیک وینئ.',
  'Gas los: verlaag tijdig je snelheid en beoordeel of je moet stoppen.': 'ګاز پرېږدئ: پر وخت سرعت کم کړئ او وارزوئ چې درېدل اړین دي که نه.',
  'Een fietser naast je wijkt onverwacht richting jouw rijstrook.': 'تر څنګ مو یو بایسکل چلوونکی ناڅاپه ستاسو د لین پر لور رااوړي.',
  'Remmen: er ontstaat direct botsingsgevaar.': 'بریک ونیسئ: د ټکر سمدستي خطر رامنځته کېږي.',
  'Het begint hard te regenen en je zicht wordt minder.': 'سخت باران پیلېږي او لید مو کمېږي.',
  'Gas los: pas je snelheid geleidelijk aan en vergroot de afstand.': 'ګاز پرېږدئ: سرعت ورو ورو برابر کړئ او واټن زیات کړئ.',
  'Een voetganger staat bij het zebrapad en wil oversteken.': 'یو پلی کس د اوښتو کرښو ته نږدې ولاړ دی او اوښتل غواړي.',
  'Remmen: geef de voetganger veilig gelegenheid om over te steken.': 'بریک ونیسئ: پلي کس ته د خوندي اوښتو فرصت ورکړئ.',
  'Je rijdt op de snelweg en ziet dat jouw rijstrook verderop ophoudt.': 'پر لویه چټکه لاره روان یاست او وینئ چې ستاسو لین مخکې پای ته رسېږي.',
  'Gas los: creëer ruimte, kijk goed en bereid het invoegen voor.': 'ګاز پرېږدئ: واټن جوړ کړئ، ښه وګورئ او بل لین ته د ننوتلو تیاری ونیسئ.',
  'Je ziet een ambulance met zwaailicht en sirene achter je naderen.': 'له شا یو امبولانس په څراغ او سیرن سره درنږدې کېږي.',
  'Gas los: maak gecontroleerd ruimte zonder plotselinge bewegingen.': 'ګاز پرېږدئ: له ناڅاپي حرکتونو پرته په کنټرول سره لاره ورکړئ.',
  'Je rijdt in dichte mist en kunt veel minder ver vooruit kijken.': 'په ګڼې لړې کې روان یاست او ډېر لږ واټن مخکې لیدلای شئ.',
  'Gas los: pas je snelheid aan de korte zichtafstand aan.': 'ګاز پرېږدئ: سرعت د لنډ لید واټن سره برابر کړئ.',
  'Je rijdt langs een school en kinderen spelen dicht bij de straat.': 'د ښوونځي ترڅنګ تېرېږئ او ماشومان سړک ته نږدې لوبې کوي.',
  'Gas los: verlaag je snelheid en wees voorbereid op onverwacht gedrag.': 'ګاز پرېږدئ: سرعت کم کړئ او ناڅاپي چلند ته چمتو اوسئ.',
  'Tussen geparkeerde auto’s stapt plotseling een voetganger de rijbaan op.': 'د پارک شویو موټرو له منځه ناڅاپه یو پلی کس سړک ته راووځي.',
  'Remmen: de voetganger bevindt zich direct in jouw rijlijn.': 'بریک ونیسئ: پلی کس نېغ ستاسو د تګ په مسیر کې دی.',
  'Meerdere auto’s verderop gaan de remlichten aan, maar jouw voorganger rijdt nog door.': 'مخکې د څو موټرو د بریک څراغونه بلېږي، خو ستاسو مخکینی موټر لا روان دی.',
  'Gas los: anticipeer op de afremmende verkeersstroom en vergroot je veiligheidsmarge.': 'ګاز پرېږدئ: د ترافیک ورو کېدو ته چمتو شئ او خوندي واټن زیات کړئ.',
  'Het verkeerslicht is groen, het kruispunt is vrij en je rijdt met aangepaste snelheid.': 'ترافیکي څراغ شین دی، څلورلاره خالي ده او په مناسب سرعت روان یاست.',
  'Niets doen: er is geen direct gevaar; blijf wel het kruispunt controleren.': 'هېڅ مه کوئ: سمدستي خطر نشته؛ خو څلورلارې ته پام ساتئ.',
  'Naast je begint iemand het portier van een geparkeerde auto te openen.': 'تر څنګ مو یو څوک د پارک شوي موټر دروازه پرانیزي.',
  'Remmen: een openslaand portier vormt onmiddellijk botsingsgevaar.': 'بریک ونیسئ: پرانیستل کېدونکې دروازه د ټکر سمدستي خطر جوړوي.',
  'Je nadert een scherpe bocht en merkt dat je snelheid te hoog is.': 'تېز کږلېچ ته نږدې کېږئ او پوهېږئ چې سرعت مو ډېر لوړ دی.',
  'Gas los: verminder vóór de bocht rustig snelheid en houd de auto stabiel.': 'ګاز پرېږدئ: له کږلېچ مخکې په ارامۍ سرعت کم کړئ او موټر ثابت وساتئ.',
  'Een bal rolt tussen geparkeerde auto’s de weg op.': 'د پارک شویو موټرو له منځه توپ سړک ته رغړي.',
  'Remmen: er kan direct een kind achter de bal aan komen.': 'بریک ونیسئ: ښايي سمدستي ماشوم په توپ پسې راووځي.',
  'Een fietser rijdt stabiel op een afgescheiden fietspad en er is voldoende afstand.': 'یو بایسکل چلوونکی په جلا بایسکل لاره ثابت روان دی او کافي واټن شته.',
  'Niets doen: er is geen direct gevaar; blijf de fietser volgen met je blik.': 'هېڅ مه کوئ: سمدستي خطر نشته؛ بایسکل چلوونکی تر نظر لاندې وساتئ.',
  'Je rijdt te dicht achter een auto die met constante snelheid rijdt.': 'په ثابت سرعت روان موټر پسې ډېر نږدې روان یاست.',
  'Gas los: vergroot geleidelijk de volgafstand zonder onnodig hard te remmen.': 'ګاز پرېږدئ: له بې‌اړتیا سخت بریک پرته واټن ورو ورو زیات کړئ.',
  'Verderop versmalt de rijbaan door wegwerkzaamheden en het verkeer rijdt nog door.': 'مخکې د سړک د کارونو له امله لاره تنګېږي او ترافیک لا روان دی.',
  'Gas los: pas tijdig je snelheid aan en zoek rustig de juiste positie.': 'ګاز پرېږدئ: پر وخت سرعت برابر کړئ او په ارامۍ سم ځای ونیسئ.',
  'Een tegenligger komt gedeeltelijk op jouw weghelft terecht.': 'مخامخ راتلونکی موټر یوه برخه ستاسو د سړک نیمې ته رااوړي.',
  'Remmen: de beschikbare ruimte wordt direct kleiner en er is botsingsgevaar.': 'بریک ونیسئ: شته ځای سمدستي کمېږي او د ټکر خطر شته.',
  'Het verkeerslicht wordt geel en je kunt nog veilig vóór de stopstreep stoppen.': 'ترافیکي څراغ ژېړ کېږي او لا د تم کرښې مخکې په خوندي ډول درېدلای شئ.',
  'Remmen: bij geel stop je wanneer dat nog veilig kan.': 'بریک ونیسئ: په ژېړ څراغ کې ودرېږئ، که دا په خوندي ډول کېدای شي.',
  'Vlak langs de weg staat een dier dat richting de rijbaan beweegt.': 'سړک ته نږدې یو څاروی د موټرو د تګ برخې پر لور خوځېږي.',
  'Gas los: verlaag je snelheid en houd rekening met onverwacht oversteken.': 'ګاز پرېږدئ: سرعت کم کړئ او ناڅاپي اوښتل په پام کې ونیسئ.',
  'Je rijdt naast een vrachtwagen die richting aangeeft om rechtsaf te slaan.': 'د داسې لارۍ ترڅنګ روان یاست چې ښي لور ته د تاوېدو اشاره کوي.',
  'Remmen: blijf uit de dode hoek en laat de vrachtwagen afslaan.': 'بریک ونیسئ: له نه لیدل کېدونکې ساحې لرې اوسئ او لارۍ تاوېدو ته پرېږدئ.',
  'Je nadert bij vorst een brugdek en ziet een waarschuwing voor gladheid.': 'په یخنۍ کې پل ته نږدې کېږئ او د ښویېدو خبرداری وینئ.',
  'Gas los: brugdekken kunnen eerder glad worden; verminder rustig snelheid.': 'ګاز پرېږدئ: د پل سطحه ښايي ژر یخه او ښویه شي؛ په ارامۍ سرعت کم کړئ.',
  'Voor je ontstaat plotseling een stilstaande file.': 'مخکې مو ناڅاپه ولاړ ترافیکي کتار جوړېږي.',
  'Remmen: het snelheidsverschil met de file vormt onmiddellijk gevaar.': 'بریک ونیسئ: له ولاړ کتار سره د سرعت توپیر سمدستي خطر جوړوي.',
  'Op de snelweg is de rijbaan vrij, je afstand is ruim en je snelheid is toegestaan.': 'پر لویه چټکه لاره لین خالي دی، واټن مو کافي دی او سرعت مو مجاز دی.',
  'Niets doen: houd koers en snelheid stabiel en blijf ver vooruit kijken.': 'هېڅ مه کوئ: مسیر او سرعت ثابت وساتئ او لرې مخکې کتل جاري وساتئ.',
  'Een bus staat bij een halte en passagiers lopen dicht langs de rijbaan.': 'بس په تمځای کې ولاړ دی او سپرلۍ د سړک د موټرو برخې ته نږدې ګرځي.',
  'Gas los: houd rekening met passagiers die onverwacht kunnen oversteken.': 'ګاز پرېږدئ: د سپرلیو ناڅاپي اوښتل په پام کې ونیسئ.',
  'Een auto rijdt achteruit vanuit een uitrit jouw rijbaan op.': 'یو موټر له وتونکې لارې په شا ستاسو لین ته راووځي.',
  'Remmen: de auto kruist direct jouw rijlijn.': 'بریک ونیسئ: موټر نېغ ستاسو د تګ مسیر پرېکوي.'
});
