// Original, educational situations. Decisions depend on the exact conditions in each prompt.
const rvv='https://wetten.overheid.nl/BWBR0004825/2026-07-01/';
export const HAZARD_SOURCES={
 h5:{title:'Wegenverkeerswet 1994 · artikel 5',url:'https://wetten.overheid.nl/BWBR0006622/2026-09-01/#HoofdstukII_Paragraaf1_Artikel5',publisher:'Overheid.nl',reviewed:'2026-09-28',effective:'2026-09-01',note:'Algemene verplichting om gevaar of hinder door verkeersgedrag te voorkomen. De oefenactie is een didactische keuze bij de omschreven omstandigheden, geen letterlijke wettelijke opdracht.'},
 h19:{title:'RVV 1990 · artikel 19',url:rvv+'#HoofdstukII_Paragraaf8_Artikel19',publisher:'Overheid.nl',reviewed:'2026-09-28',effective:'2026-07-01',note:'De bestuurder moet binnen de afstand die hij kan overzien en die vrij is kunnen stoppen. De vraag benoemt zicht en afstand expliciet.'},
 h49:{title:'RVV 1990 · artikel 49',url:rvv+'#HoofdstukII_Paragraaf19_Artikel49',publisher:'Overheid.nl',reviewed:'2026-09-28',effective:'2026-07-01',note:'Voetgangers op of duidelijk bij een voetgangersoversteekplaats laten voorgaan.'},
 h15a:{title:'RVV 1990 · artikel 15a',url:rvv+'#HoofdstukII_Paragraaf5a_Artikel15a',publisher:'Overheid.nl',reviewed:'2026-09-28',effective:'2026-07-01',note:'Een overweg niet oprijden of oversteken als dat niet veilig en zonder stilstand op de overweg kan.'}
};
const B='Remmen',G='Gas loslaten',N='Doorrijden en blijven kijken';
// id, road conditions, best immediate response, visible warning signal, explanation, source, scene.
const rows=[
 ['ball','Je rijdt 30 km/u. Vlak voor je rolt een bal tussen geparkeerde auto’s de rijbaan op. Er is nog voldoende ruimte om vóór de bal te stoppen. Wat doe je direct?',B,'Bal rolt de rijbaan op','Een kind kan achter de bal aan komen. Stop nu terwijl je nog veilig kunt stoppen.','h19',{place:'voor je',object:'bal',road:'Woonstraat'}],
 ['childsteps','Bij een school stapt een kind op korte afstand onverwacht de rijbaan op. Je kunt nog vóór het kind stoppen. Wat doe je direct?',B,'Kind stapt de rijbaan op','Het gevaar staat al op jouw rijbaan. Rem en voorkom dat je het kind raakt.','h5',{place:'voor je',object:'kind',road:'Schoolomgeving'}],
 ['zebrawalk','Een voetganger steekt vlak voor jou de zebra op en je kunt ervoor stoppen. Wat doe je?',B,'Voetganger betreedt de zebra','Laat de voetganger voorgaan en stop op tijd.','h49',{place:'voor je',object:'voetganger',road:'Zebra'}],
 ['carbrakes','De auto vlak voor je remt plotseling sterk. Je hebt genoeg afstand om veilig achter hem te stoppen. Wat doe je direct?',B,'Remlichten vlak voor je','Rem direct en houd ruimte. Alleen gas loslaten kan hier te laat zijn.','h19',{place:'voor je',object:'auto',road:'Doorgaande weg'}],
 ['cyclistfalls','Een fietser op jouw rijbaan valt op korte afstand. Je kunt vóór de fietser stoppen. Wat doe je?',B,'Fietser valt op jouw rijbaan','De rijbaan is niet meer vrij. Rem om te stoppen.','h19',{place:'voor je',object:'fiets',road:'Stadsstraat'}],
 ['dogcross','Een hond rent vlak voor je de rijbaan op. Je hebt ruimte om veilig vóór het dier te stoppen, zonder uit te wijken. Wat doe je?',B,'Dier op de rijbaan','Rem rechtuit en stop veilig. Abrupt uitwijken kan een nieuw gevaar maken.','h5',{place:'voor je',object:'dier',road:'Buitenweg'}],
 ['oncoming','Een tegemoetkomende auto wijkt onverwacht uit naar jouw rijstrook. Je hebt ruimte om op jouw strook vóór het conflict te stoppen. Wat doe je?',B,'Tegenligger op jouw strook','Rem en verminder het risico op een botsing. De andere bestuurder heeft mogelijk geen ruimte om terug te gaan.','h5',{place:'voor je',object:'auto',road:'Tweerichtingsweg'}],
 ['barrier','De rode overweglichten knipperen en de slagboom begint te sluiten. Je nadert de stopplaats met voldoende remweg. Wat doe je?',B,'Overweg sluit','Stop vóór de overweg. Rijd deze niet meer op.','h15a',{place:'voor je',object:'overweg',road:'Overweg'}],
 ['standingtraffic','Je nadert een stilstaande file. De laatste auto staat op korte afstand; je hebt voldoende ruimte om veilig erachter te stoppen. Wat doe je?',B,'Stilstaande auto’s voor je','De weg vóór je is geblokkeerd. Begin direct met remmen zodat je achteraan kunt stoppen.','h19',{place:'voor je',object:'file',road:'Autosnelweg'}],
 ['bikecuts','Een fietser snijdt plotseling vlak voor je de rijbaan over. Je kunt nog vóór de fietser stoppen. Wat doe je?',B,'Fietser kruist vlak voor je','Rem tijdig en laat de fietser vrij.','h5',{place:'voor je',object:'fiets',road:'Kruising'}],
 ['pedblind','Iemand met een witte stok met rode ringen loopt vlak voor jou de weg op. Je kunt vóór die persoon stoppen. Wat doe je?',B,'Persoon op de rijbaan','Stop op tijd en geef de persoon de ruimte om over te steken.','h5',{place:'voor je',object:'voetganger',road:'Woonstraat'}],
 ['debris','Op jouw rijstrook ligt vlak voor je een groot voorwerp. Je kunt vóór het voorwerp stoppen, maar veilig uitwijken kan niet. Wat doe je?',B,'Voorwerp op jouw rijstrook','Rem vóór het voorwerp. Uitwijken zonder vrije ruimte kan nog gevaarlijker zijn.','h19',{place:'voor je',object:'voorwerp',road:'Doorgaande weg'}],
 ['school','Je rijdt 30 km/u langs een school. Kinderen spelen op het trottoir achter geparkeerde auto’s; niemand betreedt de rijbaan. Je hebt ruim zicht en voldoende afstand. Wat doe je nu?',G,'Kinderen achter geparkeerde auto’s','Er kan plots iemand achter een auto vandaan komen. Neem tijdig gas terug en bereid je voor op remmen.','h19',{place:'langs de weg',object:'kind',road:'Schoolomgeving'}],
 ['parkeddoor','Je rijdt langs een rij geparkeerde auto’s. In één auto zit iemand dicht bij de deur; die deur blijft nog dicht. Je hebt afstand en ruimte. Wat doe je?',G,'Iemand zit bij een portier','Een deur kan opengaan. Verlaag tijdig je snelheid en houd ruimte.','h5',{place:'langs de weg',object:'auto',road:'Parkeerstrook'}],
 ['busstop','Je nadert een stilstaande bus bij een halte. Reizigers staan op het trottoir en steken nog niet over. Je hebt ruim voldoende afstand. Wat doe je nu?',G,'Bus en reizigers bij halte','Er kan iemand achter de bus vandaan komen. Neem gas terug en kijk goed.','h19',{place:'langs de weg',object:'bus',road:'Bebouwde kom'}],
 ['rainstarts','Het begint hard te regenen. De weg vóór je is nog vrij en je houdt ruim afstand. Wat doe je als eerste?',G,'Zicht verslechtert door regen','Neem gas terug en stem snelheid en afstand af op het verslechterende zicht en de grip.','h19',{place:'om je heen',object:'regen',road:'Buitenweg'}],
 ['fogfar','Er ontstaat mist verderop. Je kunt de huidige vrije weg nog goed overzien, maar je nadert het mistgebied met voldoende afstand. Wat doe je nu?',G,'Mist verderop','Bereid je vóór het mistgebied voor: neem gas terug zodat je later binnen het zicht kunt stoppen.','h19',{place:'voor je',object:'mist',road:'Autoweg'}],
 ['bend','Je nadert op afstand een onoverzichtelijke bocht. Het wegdek is vrij en je hebt ruim tijd om snelheid aan te passen. Wat doe je?',G,'Zicht verdwijnt achter de bocht','Neem voor de bocht gas terug; je moet kunnen stoppen binnen wat je kunt overzien.','h19',{place:'voor je',object:'bocht',road:'Buitenweg'}],
 ['works','Op afstand begint een versmalde werkstrook. Het is nog vrij voor je en je hebt ruimte om snelheid rustig te verminderen. Wat doe je?',G,'Werkvak vernauwt de weg','Neem gas terug en pas ruim van tevoren je snelheid aan.','h19',{place:'voor je',object:'werkvak',road:'Doorgaande weg'}],
 ['cyclistweaves','Een fietser rijdt verderop op dezelfde weg wat onzeker, maar blijft nog op zijn strook. Je hebt voldoende afstand. Wat doe je?',G,'Fietser rijdt onzeker','Neem vaart weg en vergroot de marge voor een onverwachte beweging.','h5',{place:'verderop',object:'fiets',road:'Stadsstraat'}],
 ['junctionview','Je nadert een onoverzichtelijke kruising. Jouw route is nog vrij en er staat niemand vlak voor je. Je hebt ruim tijd. Wat doe je?',G,'Kruising is moeilijk te overzien','Neem tijdig gas terug om beter te kunnen kijken en zo nodig te stoppen.','h19',{place:'voor je',object:'kruising',road:'Woonwijk'}],
 ['animalverge','In de berm staat een dier dat richting de rijbaan kijkt. Het is nog niet op de weg en je hebt voldoende afstand. Wat doe je?',G,'Dier staat dicht bij de weg','Neem gas terug en houd rekening met een plotselinge beweging.','h5',{place:'langs de weg',object:'dier',road:'Buitenweg'}],
 ['pedwaits','Iemand staat verderop bij een zebra en lijkt te willen oversteken. Je hebt ruim voldoende afstand om rustig te stoppen. Wat doe je als eerste?',G,'Voetganger wil zebra gebruiken','Neem gas terug en bereid je voor om de voetganger voor te laten gaan.','h49',{place:'verderop',object:'voetganger',road:'Zebra'}],
 ['trafficlightsfar','Je ziet op ruime afstand dat een verkeerslicht van groen naar geel wisselt. Je kunt zonder hard remmen vóór de stopstreep stoppen. Wat doe je als eerste?',G,'Verkeerslicht wisselt naar geel','Neem gas terug en bereid je voor om veilig te stoppen.','h5',{place:'verderop',object:'verkeerslicht',road:'Stadsstraat'}],
 ['openroad','Je rijdt met aangepaste snelheid. De rechte weg is ver vooruit zichtbaar en vrij; er zijn geen andere weggebruikers, versmallingen of bijzonderheden. Wat doe je nu?',N,'Geen direct gevaar zichtbaar','Houd je koers en blijf de weg observeren. Er is nu geen reden voor een extra remactie.','h19',{place:'vrije weg',object:'geen',road:'Overzichtelijke weg'}],
 ['separated','Op de andere rijbaan rijdt verkeer achter een doorlopende fysieke middenafscheiding. Jouw weg is ver vooruit vrij en je rijdt al passend. Wat doe je nu?',N,'Ander verkeer is fysiek gescheiden','Blijf kijken en rijd met aangepaste snelheid door; er is nu geen conflict op jouw rijbaan.','h5',{place:'gescheiden',object:'auto',road:'Gescheiden rijbanen'}],
 ['greenfree','Je nadert op aangepaste snelheid een groen verkeerslicht. De hele kruising is goed zichtbaar, vrij van ander verkeer en voetgangers; niemand nadert. Wat doe je nu?',N,'Kruising is vrij bij groen','Blijf controleren en rijd door. Een extra remactie is in deze omschreven situatie niet nodig.','h5',{place:'vrije weg',object:'verkeerslicht',road:'Kruising'}],
 ['emptyzebra','Je rijdt aangepast en nadert een volledig zichtbare zebra. Er is niemand op of nabij de oversteekplaats en geen voertuig belemmert het zicht. Wat doe je nu?',N,'Zebra is zichtbaar en leeg','Blijf kijken en rijd door. Je blijft voorbereid op veranderingen.','h49',{place:'vrije weg',object:'zebra',road:'Stadsstraat'}],
 ['bikebehindrail','Een fietser rijdt op een volledig gescheiden fietspad achter een doorlopend hek. Er is geen opening richting jouw rijbaan; jouw weg is vrij. Wat doe je nu?',N,'Fietser is fysiek gescheiden','De fietser kan hier niet direct jouw baan oprijden. Blijf kijken en rijd door.','h5',{place:'gescheiden',object:'fiets',road:'Stadsstraat'}],
 ['personbehindbarrier','Een voetganger loopt achter een doorlopende fysieke afscheiding zonder opening. Jouw rijbaan en de omgeving zijn overzichtelijk en vrij. Wat doe je nu?',N,'Voetganger is fysiek gescheiden','Er is geen direct oversteekconflict. Houd overzicht en rijd door.','h5',{place:'gescheiden',object:'voetganger',road:'Doorgaande weg'}],
 ['parkedopposite','Aan de andere kant van een brede weg staan auto’s geparkeerd achter een afscheiding. Jouw rijbaan is vrij en volledig zichtbaar. Wat doe je nu?',N,'Geparkeerde auto’s zijn afgescheiden','Er ontstaat in deze situatie geen direct gevaar voor jouw baan. Blijf wel alert.','h5',{place:'gescheiden',object:'auto',road:'Brede weg'}],
 ['clearcurve','Je bent de bocht al veilig uit. De weg voor je is volledig te overzien, vrij en je snelheid is passend. Wat doe je nu?',N,'Vrij zicht na de bocht','De mogelijke verrassing in de bocht is voorbij. Blijf observeren en rijd door.','h19',{place:'vrije weg',object:'geen',road:'Buitenweg'}],
 ['nohazard','Op een overzichtelijke weg rijd je ruim binnen de geldende limiet. Je hebt vrije stopafstand en ziet nergens een risico of conflict. Wat doe je nu?',N,'Vrije stopafstand','Doorrijden terwijl je blijft kijken past bij deze rustige, volledig omschreven situatie.','h19',{place:'vrije weg',object:'geen',road:'Woonwijk'}],
 ['overpass','Een voetganger steekt via een voetgangersbrug boven de weg over. Jouw rijbaan is overzichtelijk en vrij. Wat doe je nu?',N,'Voetganger gebruikt een brug','De voetganger kruist jouw rijbaan niet. Blijf kijken en rijd door.','h5',{place:'gescheiden',object:'voetganger',road:'Autoweg'}]
];
export const HAZARD_QUESTIONS=Object.fromEntries(rows.map(([id,context,action,signal,explanation,source,scene])=>[id,{id,context,action,signal,explanation,sourceIds:[source],scene}]));
export const HAZARD_CHAPTERS=[{name:'Zie het directe gevaar',description:'Reageer op wat nu voor je gebeurt.',color:'blue'},{name:'Kijk vooruit',description:'Herken risico’s vóór het misgaat.',color:'mint'},{name:'Houd overzicht',description:'Kies bewust wanneer je kunt doorrijden.',color:'violet'},{name:'Gevaarmeester',description:'Alle situaties komen samen.',color:'gold'}];
const groups=[
 ['Het signaal','reaction','ball school openroad childsteps separated'],
 ['Kijk nog eens','spot','ball carbrakes school rainstarts emptyzebra'],
 ['Wie is er op de weg?','reaction','childsteps zebrawalk cyclistfalls cyclistweaves greenfree'],
 ['Nu of straks?','reaction','dogcross animalverge pedwaits openroad busstop'],
 ['Snelle blik','timed','ball school carbrakes clearcurve pedwaits'],
 ['Zie het risico','spot','parkeddoor busstop works oncoming greenfree'],
 ['Zicht en ruimte','reaction','fogfar bend openroad debris clearcurve'],
 ['Bij de oversteek','reaction','zebrawalk pedwaits emptyzebra pedblind overpass'],
 ['Wat valt je op?','spot','barrier rainstarts cyclistweaves nohazard bikebehindrail'],
 ['Mini-boss: De Gevarenradar','miniboss','ball school carbrakes cyclistfalls bend pedwaits separated barrier'],
 ['Langs de weg','reaction','parkeddoor animalverge busstop personbehindbarrier cyclistweaves'],
 ['Verder kijken','spot','junctionview trafficlightsfar dogcross parkedopposite openroad'],
 ['Blijf bij je strook','reaction','oncoming bikecuts debris separated overpass'],
 ['Gevaar op afstand','reaction','works fogfar rainstarts trafficlightsfar nohazard'],
 ['Kijk, denk, doe','timed','pedblind school cyclistfalls bend greenfree'],
 ['De juiste reactie','reaction','standingtraffic junctionview animalverge clearcurve cyclistweaves'],
 ['Verrassing of rust','spot','childsteps pedwaits emptyzebra carbrakes nohazard'],
 ['Van zien naar doen','mixed','bikecuts busstop separated works barrier clearcurve'],
 ['Laatste oefening','mixed','oncoming fogfar openroad zebrawalk cyclistweaves parkedopposite'],
 ['Boss: De Gevarenmeester','boss','ball childsteps standingtraffic cyclistfalls school fogfar pedwaits barrier separated nohazard']
];
export const HAZARD_LEVELS=groups.map(([name,mode,codes],i)=>({id:61+i,number:i+1,worldId:'hazards',chapter:Math.floor(i/5),name,mode,codes:codes.split(' '),count:codes.split(' ').length,pass:['boss','miniboss'].includes(mode)?.8:.6,seconds:mode==='timed'?25:null,boss:['boss','miniboss'].includes(mode)}));
