// Original teaching scenarios checked against RVV 1990, version 2026-07-01.
// Every diagram is schematic; the complete conditions are given in the question.
const base='https://wetten.overheid.nl/BWBR0004825/2026-07-01/';
export const PRIORITY_SOURCES=Object.fromEntries([
 ['p15','Voorrang op kruispunten','HoofdstukII_Paragraaf5_Artikel15'],
 ['p18','Afslaan en rechtdoorgaand verkeer','HoofdstukII_Paragraaf7_Artikel18'],
 ['p49','Voetgangers laten voorgaan','HoofdstukII_Paragraaf19_Artikel49'],
 ['p54','Bijzondere manoeuvres','HoofdstukII_Paragraaf24_Artikel54'],
 ['p64','Verkeerslichten en voorrangsborden','HoofdstukIII_Paragraaf1_Artikel64'],
 ['p80','Haaientanden','HoofdstukIII_Paragraaf4_Artikel80']
].map(([id,title,anchor])=>[id,{title:'RVV · '+title,url:base+'#'+anchor,publisher:'Overheid.nl',reviewed:'2026-09-16',effective:'2026-07-01',note:'Primaire wettelijke bron voor de situaties in Wereld 2. Uitleg is in eigen woorden geschreven.'}]));
export const PRIORITY_CHAPTERS=[
 {name:'Kijk naar rechts',description:'Wie nadert er? Leer het kruispunt lezen.',color:'mint'},
 {name:'Samen de bocht om',description:'Afslaan, rechtdoor en kwetsbare weggebruikers.',color:'blue'},
 {name:'De uitzonderingen',description:'Borden, trams en bijzondere manoeuvres.',color:'violet'},
 {name:'De kruispuntmeester',description:'Overzicht houden wanneer alles samenkomt.',color:'gold'}
];
// id, conditions, correct decision, alternatives, explanation, article, other approach/type, your movement, optional sign.
const cases=[
 ['rightcar','Je rijdt rechtdoor op een gelijkwaardig kruispunt van verharde wegen. Een auto komt van rechts en rijdt rechtdoor.','De auto van rechts gaat eerst',['Jij gaat eerst','De grootste auto gaat eerst'],'Bij een gelijkwaardig kruispunt geef je als bestuurder voorrang aan een bestuurder van rechts.','p15','right','auto','straight'],
 ['leftcar','Je rijdt rechtdoor op een gelijkwaardig kruispunt van verharde wegen. Een auto komt van links en rijdt rechtdoor.','Jij gaat eerst',['De auto van links gaat eerst','Wie het hardst rijdt gaat eerst'],'Voor de andere bestuurder kom jij van rechts. Die moet jou voorrang verlenen. Controleer wel of de ander je gezien heeft.','p15','left','auto','straight'],
 ['rightbike','Je rijdt rechtdoor op een gelijkwaardig kruispunt van verharde wegen. Van rechts nadert een fietser die rechtdoor wil.','De fietser gaat eerst',['Jij gaat eerst, want je rijdt een auto','Alleen een auto van rechts gaat eerst'],'Een fietser is ook een bestuurder. Verkeer van rechts geldt dus ook voor deze fietser.','p15','right','fietser','straight'],
 ['leftbike','Je rijdt rechtdoor op een gelijkwaardig kruispunt van verharde wegen. Een fietser komt van links en rijdt rechtdoor.','Jij gaat eerst',['De fietser gaat altijd eerst','Een fietser valt nooit onder voorrangsregels'],'Ook voor fietsers geldt hier de rechtsregel. Jij komt voor de fietser van rechts.','p15','left','fietser','straight'],
 ['rightmoped','Je rijdt rechtdoor op een gelijkwaardig kruispunt van verharde wegen. Een bromfietser nadert van rechts op de rijbaan.','De bromfietser gaat eerst',['Jij gaat eerst','De bromfietser moet altijd wachten'],'Een bromfietser is een bestuurder. Op dit gelijkwaardige kruispunt verleen je hem voorrang.','p15','right','bromfietser','straight'],
 ['dirtother','Jij rijdt op een verharde weg. Een auto komt van rechts uit een onverharde zijweg. Er zijn geen borden of verkeerslichten.','Jij gaat eerst',['De auto van rechts gaat eerst','Jullie moeten allebei uitstappen'],'De bestuurder op de onverharde weg verleent voorrang aan bestuurders op de verharde weg. Dat is een uitzondering op de rechtsregel.','p15','right','auto','straight'],
 ['dirtyou','Jij rijdt vanaf een onverharde weg naar een verharde weg. Van links komt een auto. Er zijn geen borden of verkeerslichten.','De auto op de verharde weg gaat eerst',['Jij gaat eerst omdat je van rechts komt','De langzaamste auto gaat eerst'],'Vanaf een onverharde weg geef je voorrang aan bestuurders op de verharde weg, ook als zij van links komen.','p15','left','auto','straight'],
 ['wide','Je rijdt rechtdoor op een smalle verharde weg. Op het gelijkwaardige kruispunt komt van links een auto over een brede verharde weg.','Jij gaat eerst',['De auto op de brede weg gaat eerst','De breedte bepaalt altijd de voorrang'],'Een brede weg geeft op zichzelf geen voorrang. Op dit gelijkwaardige kruispunt kom jij voor de ander van rechts.','p15','left','auto','straight'],
 ['leftturn','Jij slaat links af. Een tegemoetkomende auto op dezelfde weg gaat rechtdoor. Er zijn geen lichten of voorrangsborden.','De tegemoetkomende auto gaat eerst',['Jij gaat eerst omdat je afslaat','Wie als eerste richting aangeeft gaat eerst'],'Bij afslaan laat je verkeer op dezelfde weg dat je tegemoetkomt voorgaan.','p18','top','auto','left'],
 ['rightturnbike','Jij slaat rechts af. Een fietser rijdt rechts naast je op dezelfde weg rechtdoor. Er zijn geen verkeerslichten.','De fietser gaat eerst',['Jij gaat eerst omdat je vooraan rijdt','De fietser moet voor elke auto stoppen'],'Bij afslaan laat je het rechtdoorgaande verkeer naast je op dezelfde weg voorgaan. Let ook op de dode hoek.','p18','along','fietser','right'],
 ['rightturnwalk','Jij slaat rechts af. Een voetganger loopt rechts naast je op dezelfde weg rechtdoor en steekt de zijstraat over. Er zijn geen verkeerslichten.','De voetganger gaat eerst',['Jij gaat eerst omdat een voetganger geen bestuurder is','Alleen op een zebra moet je wachten'],'Bij afslaan gaat het om verkeer op dezelfde weg, dus ook om voetgangers die daar rechtdoor gaan.','p18','along','voetganger','right'],
 ['shortturn','Jij slaat links af. Een tegemoetkomende auto op dezelfde weg slaat naar rechts af, dezelfde zijstraat in. Er zijn geen verkeerslichten.','De rechts afslaande auto gaat eerst',['Jij gaat eerst','De auto met de grootste draaicirkel gaat eerst'],'Een links afslaande bestuurder laat een tegemoetkomende rechts afslaande bestuurder op hetzelfde kruispunt voorgaan. Dit geldt hier voor beide auto’s.','p18','top','auto','left'],
 ['walkopposite','Jij slaat links af. Een voetganger komt je op dezelfde weg tegemoet en loopt rechtdoor over de zijstraat die jij in wilt. Er zijn geen verkeerslichten.','De voetganger gaat eerst',['Jij gaat eerst','De voetganger moet wachten omdat jij links afslaat'],'Ook tegemoetkomende voetgangers op dezelfde weg laat je bij afslaan voorgaan.','p18','top','voetganger','left'],
 ['bikeopposite','Jij slaat links af. Een tegemoetkomende fietser op dezelfde weg rijdt rechtdoor. Er zijn geen verkeerslichten.','De fietser gaat eerst',['Jij gaat eerst','Alleen tegemoetkomende auto’s gaan eerst'],'De tegemoetkomende fietser rijdt op dezelfde weg rechtdoor. Jij slaat af en laat hem voorgaan.','p18','top','fietser','left'],
 ['zebra','Je nadert een zebra zonder verkeerslichten. Een voetganger staat op het punt om daar over te steken.','De voetganger gaat eerst',['Jij gaat eerst zolang de voetganger nog niet op de zebra staat','De voetganger gaat alleen voor bij een handgebaar'],'Je laat ook voetgangers voorgaan die kennelijk op het punt staan de zebra te gebruiken. Wacht dus niet tot iemand al op de rijbaan staat.','p49','right','voetganger','straight'],
 ['zebrawalk','Je nadert een zebra zonder verkeerslichten. Een voetganger steekt al over.','Je laat de voetganger voorgaan',['Je rijdt vóór de voetganger langs','Je toetert en rijdt door'],'Voetgangers die op een zebra oversteken laat je voorgaan. Geef genoeg ruimte om veilig over te steken.','p49','right','voetganger','straight'],
 ['blind','Iemand met een witte stok met rode ringen wil oversteken. Er is geen zebra of verkeerslicht.','Je laat die persoon voorgaan',['Je rijdt door omdat er geen zebra is','Je laat alleen bestuurders voorgaan'],'Een blinde die herkenbaar is aan een witte stok met rode ringen laat je voorgaan. Daarvoor is geen zebra nodig.','p49','right','voetganger','straight'],
 ['difficult','Een voetganger die zich zichtbaar moeilijk voortbeweegt wil oversteken. Er is geen zebra of verkeerslicht.','Je laat de voetganger voorgaan',['Je rijdt door omdat er geen zebra is','Je hebt altijd voorrang in een auto'],'Bestuurders laten personen die zich moeilijk voortbewegen voorgaan. Geef tijd en ruimte.','p49','right','voetganger','straight'],
 ['tramleft','Op een gelijkwaardig kruispunt rijdt een tram van links rechtdoor. Jij wilt ook rechtdoor. Er zijn geen verkeerslichten of voorrangsborden.','De tram gaat eerst',['Jij gaat eerst omdat je van rechts komt','Een tram volgt altijd dezelfde rechtsregel als een auto'],'De tram vormt hier een uitzondering: bestuurders verlenen voorrang aan bestuurders van een tram.','p15','left','tram','straight'],
 ['tramright','Op een gelijkwaardig kruispunt rijdt een tram van rechts rechtdoor. Er zijn geen verkeerslichten of voorrangsborden.','De tram gaat eerst',['Jij gaat eerst','De tram moet altijd wachten bij een kruising'],'Je verleent hier voorrang aan de tram. De tram heeft op dit ongeregelde kruispunt ook voorrang als hij van links zou komen.','p15','right','tram','straight'],
 ['yieldleft','Jij nadert bord B6. Op de kruisende weg komt een auto van links. Er zijn geen verkeerslichten.','De auto van links gaat eerst',['Jij gaat eerst omdat je van rechts komt','Je hoeft alleen voor rechts te wachten'],'B6 verplicht je voorrang te verlenen aan bestuurders op de kruisende weg, uit beide richtingen.','rvv','left','auto','straight','B6'],
 ['yieldbike','Jij nadert bord B6. Op de kruisende weg komt een fietser van rechts. Er zijn geen verkeerslichten.','De fietser gaat eerst',['B6 geldt alleen voor auto’s','Jij gaat eerst'],'Bij B6 geef je ook fietsers op de kruisende weg voorrang: zij zijn bestuurders.','rvv','right','fietser','straight','B6'],
 ['teeth','Voor jouw kruising staan haaientanden. Van links nadert een auto op de kruisende weg. Er zijn geen verkeerslichten.','De auto van links gaat eerst',['Haaientanden zijn alleen versiering','Jij gaat eerst omdat je van rechts komt'],'Haaientanden betekenen dat je voorrang verleent aan bestuurders op de kruisende weg.','p80','left','auto','straight'],
 ['stop','Jij nadert B7 met een stopstreep. De kruising is helemaal leeg.','Je stopt volledig vóór de stopstreep',['Je rolt langzaam door','Je stopt alleen als iemand nadert'],'B7 verplicht je ook zonder ander verkeer volledig te stoppen. Daarna verleen je zo nodig voorrang. Bij een stopstreep stop je daarvoor.','rvv','none','auto','straight','B7'],
 ['stopbusy','Je bent bij B7 volledig gestopt. Op de kruisende weg nadert nu een auto van links.','Je wacht en laat de auto eerst gaan',['Je rijdt direct door omdat je al gestopt bent','De ander moet wachten omdat jij eerder stopte'],'Stoppen maakt de voorrangsplicht niet ongedaan. B7 betekent stoppen én voorrang verlenen.','rvv','left','auto','straight','B7'],
 ['exit','Je rijdt uit een duidelijk herkenbare uitrit over een doorlopend trottoir. Een voetganger loopt op dat trottoir langs de uitrit.','De voetganger gaat eerst',['Jij gaat eerst omdat een voetganger geen bestuurder is','Alleen auto’s moet je laten voorgaan'],'Een uitrit verlaten is een bijzondere manoeuvre. Je laat al het overige verkeer voorgaan, inclusief voetgangers.','p54','right','voetganger','straight'],
 ['parking','Je rijdt weg uit een parkeervak. Een fietser nadert op de rijbaan achter je.','De fietser gaat eerst',['Jij gaat eerst zodra je richting aangeeft','De fietser moet voor een wegrijdende auto stoppen'],'Bij wegrijden laat je al het overige verkeer voorgaan. Een richtingaanwijzer geeft geen voorrang.','p54','along','fietser','right'],
 ['reverse','Je rijdt achteruit uit een parkeervak. Een voetganger loopt achter je langs.','Je stopt en laat de voetganger voorgaan',['De voetganger wacht altijd voor achteruitrijlichten','Jij gaat eerst omdat je al beweegt'],'Achteruitrijden is een bijzondere manoeuvre. Daarbij laat je al het overige verkeer voorgaan.','p54','right','voetganger','straight'],
 ['merge','Je wilt vanaf een invoegstrook de doorgaande rijbaan oprijden. Naast je rijdt een auto op die rijbaan.','Je laat de auto op de rijbaan voorgaan',['Je hebt voorrang omdat je strook ophoudt','Richting aangeven geeft jou voorrang'],'Invoegen is een bijzondere manoeuvre. De auto op de doorgaande rijbaan hoeft jou geen voorrang te geven. Kies zelf een veilige ruimte.','p54','along','auto','straight'],
 ['green','Jij hebt groen bij een werkend verkeerslicht. Er staat ook B6. Gaat het verkeerslicht boven dit voorrangsbord?','Ja, het verkeerslicht gaat boven B6',['Nee, B6 gaat altijd boven groen','Alleen als er geen fietsers zijn'],'Verkeerslichten gaan boven verkeersborden die de voorrang regelen. Blijf wel letten op afslaand verkeer en een vrije doorgang.','p64','none','auto','straight','B6'],
 ['roundabout','Je nadert alleen bord D1: de verplichte rijrichting op een rotonde. Regelt dit bord op zichzelf de voorrang?','Nee, bekijk ook de voorrangsregeling',['Ja, verkeer op de rotonde gaat hierdoor altijd eerst','Ja, oprijdend verkeer heeft hierdoor altijd voorrang'],'D1 regelt de rijrichting. De voorrang volgt uit overige tekens en toepasselijke regels. Kijk bijvoorbeeld naar B6 en haaientanden.','rvv','none','auto','straight','D1'],
 ['pedright','Je rijdt rechtdoor op een gelijkwaardig kruispunt. Een gewone voetganger komt uit de zijstraat van rechts en wil jouw weg oversteken. Er is geen zebra, uitrit of verkeerslicht; de voetganger beweegt normaal en heeft geen witte stok. Geldt hier voor die voetganger de rechtsregel?','Nee, die rechtsregel gaat over bestuurders',['Ja, iedereen van rechts heeft voorrang','Ja, voetgangers hebben altijd voorrang'],'De rechtsregel op kruispunten gaat over bestuurders. Een voetganger is geen bestuurder. Andere regels kunnen voetgangers wel beschermen; blijf altijd voorzichtig.','p15','right','voetganger','straight']
];
export const PRIORITY_QUESTIONS=Object.fromEntries(cases.map(([id,context,answer,wrong,explanation,source,approach,other,movement,sign])=>[id,{id,context,answer,wrong,explanation,sourceIds:[source],approach,other,movement,sign:sign||null}]));
const groups=[
 ['Rechts in beeld','priority','rightcar leftcar rightbike leftbike rightmoped'],
 ['Ook fietsers tellen','priority','rightbike leftbike rightmoped rightcar pedright'],
 ['De regel erachter','rule','rightcar leftcar rightbike wide dirtother'],
 ['Verhard of onverhard','priority','dirtother dirtyou wide rightcar leftcar'],
 ['Rechtsradar','timed','rightcar leftbike dirtyou rightmoped wide'],
 ['Afslaan met aandacht','priority','leftturn rightturnbike rightturnwalk shortturn bikeopposite'],
 ['Wie gaat eerst?','order','leftturn shortturn rightturnbike walkopposite bikeopposite'],
 ['Voetgangers zien','priority','rightturnwalk zebra zebrawalk blind difficult'],
 ['Leg het uit','rule','rightturnbike shortturn zebra blind pedright'],
 ['Mini-boss: De Kruispuntwachter','miniboss','rightcar dirtyou rightturnwalk shortturn zebra blind leftbike wide'],
 ['De tram komt eraan','priority','tramleft tramright rightcar leftcar rightbike'],
 ['Tekens maken verschil','priority','yieldleft yieldbike teeth stop stopbusy'],
 ['Stop, kijk, beslis','order','yieldleft teeth stopbusy rightbike tramleft'],
 ['Uitritten en wegrijden','priority','exit parking reverse merge rightturnwalk'],
 ['Voorrangsreflex','timed','tramleft yieldleft exit merge shortturn'],
 ['Licht en rotonde','rule','green roundabout yieldleft stop teeth'],
 ['Kwetsbaar verkeer','priority','blind difficult rightturnwalk bikeopposite exit'],
 ['Kruispuntpuzzel','order','dirtyou tramright leftcar rightturnbike shortturn'],
 ['Klaar voor de meester','mixed','green roundabout reverse pedright stopbusy rightmoped'],
 ['Boss: De Voorrangsmeester','boss','tramleft rightbike dirtyou rightturnwalk shortturn blind teeth exit green roundabout']
];
export const PRIORITY_LEVELS=groups.map(([name,mode,codes],i)=>({id:21+i,number:i+1,worldId:'priority',chapter:Math.floor(i/5),name,mode,codes:codes.split(' '),count:codes.split(' ').length,pass:['boss','miniboss'].includes(mode)?.8:.6,seconds:mode==='timed'?25:null,boss:['boss','miniboss'].includes(mode)}));
