-- Complete lessons 11-20 with bilingual rules, tips, quizzes and corrected media.

BEGIN;

WITH data (
  lesson_number, summary_nl, summary_fa, rule_nl, rule_fa, tip_nl, tip_fa, image_src,
  question_nl, question_fa,
  option_1_nl, option_1_fa, option_2_nl, option_2_fa, option_3_nl, option_3_fa,
  correct_option, explanation_nl, explanation_fa
) AS (
  VALUES
    (11, 'Bestuurders houden zoveel mogelijk rechts, behalve wanneer een verkeerssituatie een andere plaats nodig maakt.', 'رانندگان تا حد ممکن سمت راست حرکت می‌کنند، مگر اینکه وضعیت ترافیک جای دیگری را لازم کند.', 'Rijd na een inhaalactie terug naar rechts zodra dat veilig kan en blijf niet onnodig links rijden.', 'پس از سبقت، به محض ایمن بودن به راست برگردید و بی‌دلیل چپ نمانید.', 'Kijk ver vooruit: een vrije rechterrijstrook betekent meestal dat je naar rechts terug kunt.', 'دورتر را نگاه کنید؛ خط راست آزاد معمولاً یعنی می‌توانید به راست برگردید.', '/images/theory-006-right-position.webp', 'De rechterrijstrook is vrij nadat je hebt ingehaald. Wat doe je?', 'پس از سبقت خط راست آزاد است. چه می‌کنید؟', 'Onnodig links blijven rijden', 'بی‌دلیل چپ می‌مانید', 'Veilig teruggaan naar rechts', 'با ایمنی به راست برمی‌گردید', 'Op de vluchtstrook rijden', 'روی شانه اضطراری می‌روید', 1, 'Bestuurders houden zoveel mogelijk rechts en gaan na het inhalen terug zodra dat veilig kan.', 'رانندگان تا حد ممکن راست می‌روند و پس از سبقت وقتی ایمن است به راست برمی‌گردند.'),
    (12, 'Kies tijdig de rijstrook die past bij je bestemming, pijlen en borden.', 'خطی را به‌موقع انتخاب کنید که با مقصد، پیکان‌ها و تابلوها هماهنگ باشد.', 'Volg voorsorteerpijlen en rijstrookborden en wissel alleen wanneer voldoende vrije ruimte aanwezig is.', 'پیکان‌های خط و تابلوها را دنبال کنید و فقط با فضای آزاد کافی خط را عوض کنید.', 'Een vroege rijstrookkeuze voorkomt plotseling sturen vlak voor een kruispunt of afrit.', 'انتخاب زودهنگام خط از چرخش ناگهانی نزدیک تقاطع یا خروجی جلوگیری می‌کند.', '/images/theory-007-choose-lane.webp', 'Je moet rechtsaf en boven één rijstrook staat een pijl naar rechts. Welke strook kies je?', 'باید به راست بپیچید و بالای یک خط پیکان راست است. کدام خط را می‌گیرید؟', 'De rijstrook met de pijl naar rechts', 'خط دارای پیکان راست', 'Altijd de meest linkse strook', 'همیشه چپ‌ترین خط', 'De vluchtstrook', 'شانه اضطراری', 0, 'Pijlen en rijstrookborden helpen je de strook voor de gewenste richting te kiezen.', 'پیکان‌ها و تابلوهای خط به انتخاب خط مناسب جهت کمک می‌کنند.'),
    (13, 'Voorsorteren betekent dat je vóór het afslaan tijdig en veilig de juiste positie inneemt.', 'آماده شدن برای پیچیدن یعنی پیش از پیچ، به‌موقع و ایمن در جای درست قرار بگیرید.', 'Kijk in spiegels en dode hoek, geef richting aan en verplaats geleidelijk naar het juiste voorsorteervak.', 'آینه‌ها و نقطه کور را ببینید، راهنما بزنید و آرام وارد خط مناسب شوید.', 'Voorsorteren geeft geen voorrang; verkeer op de rijstrook waarheen je gaat blijft voorgaan.', 'قرار گرفتن در خط پیچ حق تقدم نمی‌دهد؛ ترافیک خط مقصد حق تقدم دارد.', '/images/theory-008-presort-left.webp', 'Wat doe je vóórdat je naar een voorsorteervak verplaatst?', 'پیش از رفتن به خط مخصوص پیچ چه می‌کنید؟', 'Alleen claxonneren', 'فقط بوق می‌زنید', 'Spiegels en dode hoek controleren en richting aangeven', 'آینه‌ها و نقطه کور را می‌بینید و راهنما می‌زنید', 'Direct sturen zonder te kijken', 'بدون نگاه فوری می‌پیچید', 1, 'Een rijstrookwisseling vraagt eerst waarnemen, richting aangeven en voldoende vrije ruimte.', 'تغییر خط ابتدا دیدن، راهنما زدن و فضای آزاد کافی می‌خواهد.'),
    (14, 'Een fietsstrook herken je aan het fietssymbool; parkeren op een fietsstrook is verboden.', 'خط دوچرخه با نماد دوچرخه شناخته می‌شود؛ پارک روی آن ممنوع است.', 'Controleer vóór het kruisen van een fietsstrook spiegels en dode hoek en hinder geen fietsers.', 'پیش از عبور از خط دوچرخه آینه‌ها و نقطه کور را ببینید و مزاحم دوچرخه‌سوار نشوید.', 'Let bij rechts afslaan extra op fietsers die naast of schuin achter je rechtdoor rijden.', 'هنگام پیچ راست به دوچرخه‌سوار کنار یا عقب که مستقیم می‌رود توجه ویژه کنید.', '/images/theory-009-cycle-lane.webp', 'Mag je op een fietsstrook met fietssymbool parkeren?', 'آیا می‌توانید روی خط دوچرخه دارای نماد دوچرخه پارک کنید؟', 'Ja, met alarmlichten', 'بله، با چراغ خطر', 'Nee', 'خیر', 'Alleen vijf minuten', 'فقط پنج دقیقه', 1, 'Parkeren op een fietsstrook is verboden.', 'پارک کردن روی خط دوچرخه ممنوع است.'),
    (15, 'Een rijstrook met BUS of LIJNBUS is bestemd voor de aangegeven categorieën.', 'خط دارای نوشته BUS یا LIJNBUS برای دسته‌های اعلام‌شده است.', 'Gebruik een busstrook niet met een personenauto, tenzij een bord of onderbord dat uitdrukkelijk toestaat.', 'با موتر سواری از خط بس استفاده نکنید، مگر تابلو صریحاً اجازه دهد.', 'Lees zowel de wegmarkering als onderborden; uitzonderingen moeten duidelijk zijn aangegeven.', 'هم نوشته روی راه و هم تابلوهای زیرین را بخوانید؛ استثنا باید روشن اعلام شود.', '/images/theory-010-bus-lane.webp', 'Mag je met een gewone personenauto over een busstrook rijden zonder aangegeven uitzondering?', 'آیا با موتر سواری عادی بدون استثنای اعلام‌شده می‌توانید در خط بس بروید؟', 'Ja, altijd', 'بله، همیشه', 'Nee', 'خیر', 'Alleen als je haast hebt', 'فقط اگر عجله دارید', 1, 'Een busstrook is voor de aangegeven buscategorie; ander verkeer gebruikt deze alleen bij een expliciete uitzondering.', 'خط بس برای دسته اعلام‌شده است و ترافیک دیگر فقط با استثنای صریح می‌تواند استفاده کند.'),
    (16, 'Invoegen is een bijzondere manoeuvre; verkeer op de doorgaande rijbaan gaat voor.', 'ادغام یک مانور ویژه است؛ ترافیک خط اصلی حق تقدم دارد.', 'Gebruik de invoegstrook om snelheid aan te passen, kijk in spiegels en dode hoek en kies een veilige ruimte.', 'از خط ورودی برای هماهنگ کردن سرعت استفاده کنید، آینه و نقطه کور را ببینید و فضای ایمن انتخاب کنید.', 'Richting aangeven maakt je bedoeling zichtbaar maar verplicht andere bestuurders niet om ruimte te geven.', 'راهنما قصد شما را نشان می‌دهد اما دیگران را مجبور به راه دادن نمی‌کند.', '/images/Invoegen op de Nederlandse snelweg.jpg', 'Wie moet voorrang verlenen bij invoegen?', 'هنگام ادغام چه کسی باید راه بدهد؟', 'De invoegende bestuurder', 'راننده واردشونده', 'Altijd het verkeer op de doorgaande rijbaan', 'همیشه ترافیک خط اصلی', 'Degene met het grootste voertuig', 'وسیله بزرگ‌تر', 0, 'Invoegen is een bijzondere manoeuvre; de invoegende bestuurder laat al het overige verkeer voorgaan.', 'ادغام مانور ویژه است و راننده واردشونده باید به دیگران راه بدهد.'),
    (17, 'Bereid uitvoegen vroeg voor, geef rechts richting aan en rijd via de uitrijstrook.', 'خروج را زود آماده کنید، راهنمای راست بزنید و از خط خروج بروید.', 'Kies tijdig de juiste strook en verminder snelheid pas op de uitrijstrook als de situatie dat toelaat.', 'به‌موقع خط درست را بگیرید و اگر وضعیت اجازه می‌دهد سرعت را پس از ورود به خط خروج کم کنید.', 'Plotseling remmen op de doorgaande rijbaan kan achteropkomend verkeer verrassen.', 'ترمز ناگهانی در خط اصلی می‌تواند ترافیک پشت سر را غافلگیر کند.', '/images/theory-037-motorway-exit.webp', 'Wanneer geef je richting aan bij het verlaten van de autosnelweg?', 'هنگام خروج از بزرگراه چه زمانی راهنما می‌زنید؟', 'Tijdig vóór het uitvoegen', 'به‌موقع پیش از خروج', 'Pas na de afrit', 'فقط بعد از خروجی', 'Nooit', 'هرگز', 0, 'Geef tijdig rechts richting aan zodat anderen weten dat je naar de uitrijstrook gaat.', 'به‌موقع راهنمای راست بزنید تا دیگران بدانند وارد خط خروج می‌شوید.'),
    (18, 'Van rijstrook wisselen doe je alleen na kijken, richting aangeven en een dodehoekcontrole.', 'تغییر خط فقط پس از دیدن، راهنما زدن و بررسی نقطه کور انجام می‌شود.', 'Verkeer dat al op de andere rijstrook rijdt gaat voor; houd snelheid en stuurbeweging voorspelbaar.', 'ترافیکی که از قبل در خط دیگر است حق تقدم دارد؛ سرعت و فرمان را قابل پیش‌بینی نگه دارید.', 'Controleer na de spiegels vlak vóór het sturen nog eenmaal de dode hoek.', 'پس از آینه‌ها، درست پیش از چرخاندن فرمان یک بار دیگر نقطه کور را ببینید.', '/images/theory-030-lane-change.webp', 'Geeft richting aangeven je voorrang bij het wisselen van rijstrook?', 'آیا راهنما زدن هنگام تغییر خط به شما حق تقدم می‌دهد؟', 'Ja', 'بله', 'Nee', 'خیر', 'Alleen overdag', 'فقط روزها', 1, 'Richting aangeven kondigt je manoeuvre aan, maar geeft geen voorrang.', 'راهنما مانور را اعلام می‌کند اما حق تقدم نمی‌دهد.'),
    (19, 'In de dode hoek kunnen fietsers, motoren of auto’s buiten het zicht van je spiegels rijden.', 'در نقطه کور دوچرخه، موتورسیکلت یا موتر می‌تواند بیرون دید آینه باشد.', 'Controleer de dode hoek vóór afslaan of zijwaarts verplaatsen, vooral naast vrachtwagens en fietsers.', 'پیش از پیچ یا حرکت جانبی نقطه کور را ببینید، به‌ویژه کنار کامیون و دوچرخه.', 'Blijf zelf ook uit de dode hoek van grote voertuigen en zoek oogcontact waar mogelijk.', 'خودتان نیز از نقطه کور وسایل بزرگ دور بمانید و در صورت امکان تماس چشمی بگیرید.', '/images/Dode hoek_ twee fietsposities naast vrachtwagen.jpg', 'Waarom is alleen in de buitenspiegel kijken niet altijd genoeg?', 'چرا فقط نگاه کردن به آینه بیرون همیشه کافی نیست؟', 'Omdat er verkeer in de dode hoek kan zitten', 'چون ممکن است ترافیک در نقطه کور باشد', 'Omdat spiegels alleen snelheid tonen', 'چون آینه فقط سرعت را نشان می‌دهد', 'Omdat richting aangeven dan niet werkt', 'چون راهنما کار نمی‌کند', 0, 'De dode hoek is het gebied dat niet volledig in de spiegels zichtbaar is.', 'نقطه کور بخشی است که در آینه‌ها کامل دیده نمی‌شود.'),
    (20, 'Geef tijdig richting aan bij afslaan, wegrijden, inhalen en andere belangrijke zijdelingse verplaatsingen.', 'هنگام پیچ، حرکت، سبقت و جابه‌جایی جانبی مهم به‌موقع راهنما بزنید.', 'Zet de richtingaanwijzer zo dat anderen je plan vroeg begrijpen en schakel hem na de manoeuvre uit.', 'راهنما را طوری بزنید که دیگران زود قصد شما را بفهمند و پس از مانور خاموشش کنید.', 'Een richtingaanwijzer vervangt nooit kijken en geeft geen voorrang.', 'راهنما هرگز جای نگاه کردن را نمی‌گیرد و حق تقدم نمی‌دهد.', '/images/Rotonde verlaten met rechter richtingaanwijzer.jpg', 'Wat betekent het als je richting aangeeft?', 'راهنما زدن چه معنی دارد؟', 'Dat je automatisch voorrang hebt', 'اینکه خودکار حق تقدم دارید', 'Dat je jouw voorgenomen richting zichtbaar maakt', 'اینکه جهت موردنظر خود را نشان می‌دهید', 'Dat anderen verplicht moeten stoppen', 'اینکه دیگران حتماً باید توقف کنند', 1, 'Richting aangeven informeert anderen, maar verandert de voorrangsregels niet.', 'راهنما دیگران را آگاه می‌کند اما قواعد حق تقدم را تغییر نمی‌دهد.')
), release AS (SELECT id FROM content_releases WHERE version = 1)
UPDATE course_lessons AS lesson
SET summary=jsonb_build_object('nl',data.summary_nl,'fa',data.summary_fa),
    content_blocks=jsonb_build_array(
      jsonb_build_object('type','rule','text',jsonb_build_object('nl',data.rule_nl,'fa',data.rule_fa)),
      jsonb_build_object('type','exam_tip','text',jsonb_build_object('nl',data.tip_nl,'fa',data.tip_fa)),
      jsonb_build_object('type','quiz','question',jsonb_build_object('nl',data.question_nl,'fa',data.question_fa),
        'options',jsonb_build_array(
          jsonb_build_object('nl',data.option_1_nl,'fa',data.option_1_fa),
          jsonb_build_object('nl',data.option_2_nl,'fa',data.option_2_fa),
          jsonb_build_object('nl',data.option_3_nl,'fa',data.option_3_fa)),
        'correctOption',data.correct_option,'explanation',jsonb_build_object('nl',data.explanation_nl,'fa',data.explanation_fa))),
    media=jsonb_build_array(jsonb_build_object('type','image','src',data.image_src,'alt',lesson.title)),updated_at=NOW()
FROM data,release WHERE lesson.release_id=release.id AND lesson.lesson_number=data.lesson_number;

DO $check$ DECLARE valid_count integer; BEGIN
  SELECT count(*) INTO valid_count FROM course_lessons
  WHERE release_id=(SELECT id FROM content_releases WHERE version=1) AND lesson_number BETWEEN 11 AND 20
    AND content_blocks->2->>'type'='quiz' AND jsonb_array_length(content_blocks->2->'options')=3;
  IF valid_count<>10 THEN RAISE EXCEPTION 'Road-position lessons validation failed: %',valid_count; END IF;
END $check$;

INSERT INTO schema_migrations(version,name) VALUES(10,'road_position_lessons') ON CONFLICT(version) DO NOTHING;
COMMIT;

