-- Complete lessons 41-50 with bilingual intersection and conflict rules.
BEGIN;
WITH data (lesson_number,summary_nl,summary_fa,rule_nl,rule_fa,tip_nl,tip_fa,question_nl,question_fa,option_1_nl,option_1_fa,option_2_nl,option_2_fa,option_3_nl,option_3_fa,correct_option,explanation_nl,explanation_fa) AS (VALUES
 (41,'Op een gelijkwaardig kruispunt gaat verkeer van rechts voor.','در تقاطع هم‌ارزش، ترافیک از راست مقدم است.','Pas deze regel toe als er geen borden, haaientanden of lichten zijn die de voorrang regelen.','این قاعده را وقتی اجرا کنید که تابلو، دندان کوسه یا چراغ تقدم را تعیین نکند.','Verlaag je snelheid zodat je het kruispunt kunt overzien.','سرعت را کم کنید تا تقاطع را کامل ببینید.','Wie gaat voor op een gelijkwaardig kruispunt?','در تقاطع هم‌ارزش چه کسی مقدم است؟','Verkeer van rechts','ترافیک از راست','Verkeer van links','ترافیک از چپ','De snelste bestuurder','سریع‌ترین راننده',0,'Zonder andere regeling heeft verkeer van rechts voorrang.','بدون مقررات دیگر، ترافیک از راست حق تقدم دارد.'),
 (42,'Voorrang op een kruispunt wordt bepaald door borden en wegmarkeringen.','حق تقدم در تقاطع با تابلو و خط‌کشی تعیین می‌شود.','Een voorrangsbord of haaientanden gaan vóór de algemene regel rechts gaat voor.','تابلو تقدم یا دندان‌های کوسه بر قاعده تقدم از راست مقدم است.','Zoek de tekens al vóór het kruispunt op.','نشانه‌ها را پیش از رسیدن به تقاطع پیدا کنید.','Wat gaat vóór de regel rechts gaat voor?','چه چیزی بر قاعده تقدم از راست مقدم است؟','Een voorrangsbord of haaientanden','تابلو تقدم یا دندان کوسه','De kleur van de auto','رنگ خودرو','De breedte van de auto','عرض خودرو',0,'Borden en haaientanden regelen de voorrang en hebben voorrang op de basisregel.','تابلو و دندان کوسه تقدم را تنظیم می‌کنند و بر قاعده پایه مقدم‌اند.'),
 (43,'Verkeerslichten regelen de doorgang zolang ze werken.','چراغ‌های راهنمایی تا زمانی که کار می‌کنند عبور را تنظیم می‌کنند.','Rood betekent stoppen, groen betekent doorgaan als het kruispunt vrij is en geel betekent stoppen als dat veilig kan.','قرمز یعنی توقف، سبز عبور در صورت آزاد بودن تقاطع و زرد توقف اگر ایمن باشد.','Blokkeer een kruispunt niet, ook niet bij groen licht.','حتی با چراغ سبز تقاطع را مسدود نکنید.','Wat betekent rood verkeerslicht?','چراغ قرمز چه معنایی دارد؟','Stoppen','توقف','Versnellen','شتاب گرفتن','Parkeren op het kruispunt','پارک در تقاطع',0,'Bij rood moet je vóór de stopstreep stoppen.','در چراغ قرمز باید پیش از خط ایست توقف کنید.'),
 (44,'Bij afslaan moet je richting aangeven en kruisend verkeer voor laten gaan.','هنگام پیچیدن باید راهنما بزنید و به ترافیک متقاطع راه بدهید.','Sla pas af nadat je fietsers en voetgangers op de kruisende weg hebt gecontroleerd.','فقط پس از بررسی دوچرخه‌سوار و عابر در مسیر متقاطع بپیچید.','Kijk over je schouder naar de dode hoek vóór je afslaat.','پیش از پیچیدن از روی شانه نقطه کور را بررسی کنید.','Wat doe je vóór afslaan?','پیش از پیچیدن چه می‌کنید؟','Richting aangeven en kruisend verkeer voor laten gaan','راهنما زدن و دادن تقدم به ترافیک متقاطع','Alleen claxonneren','فقط بوق زدن','Gas geven','گاز دادن',0,'Afslaan vraagt richting aangeven, spiegels kijken en voorrang geven aan kruisende weggebruikers.','پیچیدن نیازمند راهنما، نگاه در آینه و دادن تقدم به کاربران متقاطع است.'),
 (45,'Rechtdoor op dezelfde weg gaat vóór afslaand verkeer.','حرکت مستقیم در همان راه بر ترافیکِ در حال پیچیدن مقدم است.','Wie afslaat moet bestuurders, fietsers en voetgangers die rechtdoor gaan op dezelfde weg voor laten gaan.','راننده‌ای که می‌پیچد باید به راننده، دوچرخه‌سوار و عابری که مستقیم در همان راه می‌رود راه بدهد.','Let op fietsers naast je, ook als zij op een fietsstrook rijden.','مراقب دوچرخه‌سواران کنار خود باشید، حتی در مسیر دوچرخه.','Wie heeft voorrang bij rechtdoor op dezelfde weg?','در حرکت مستقیم در همان راه چه کسی مقدم است؟','Het afslaande verkeer','ترافیکِ در حال پیچیدن','Het verkeer dat rechtdoor gaat','ترافیک مستقیم','De bestuurder achter je','راننده پشت سر',1,'Afslaand verkeer verleent voorrang aan verkeer dat rechtdoor gaat op dezelfde weg.','ترافیک در حال پیچیدن به ترافیک مستقیم در همان راه تقدم می‌دهد.'),
 (46,'Bij een T-splitsing gelden dezelfde voorrangsregels als bij andere kruispunten.','در سه‌راهی همان قواعد تقدم تقاطع‌های دیگر اعمال می‌شود.','Een doorgaande weg heeft niet automatisch voorrang; kijk naar borden, haaientanden en verkeer van rechts.','راه مستقیم خودبه‌خود مقدم نیست؛ تابلو، دندان کوسه و ترافیک از راست را بررسی کنید.','Behandel een T-splitsing niet als een uitzondering.','سه‌راهی را استثنا فرض نکنید.','Heeft de doorgaande weg bij een T-splitsing altijd voorrang?','آیا راه مستقیم در سه‌راهی همیشه مقدم است؟','Ja, altijd','بله، همیشه','Nee, borden en regels bepalen dat','خیر، تابلو و قواعد تعیین می‌کنند','Alleen in het donker','فقط در تاریکی',1,'Een T-vorm alleen bepaalt de voorrang niet.','شکل T به‌تنهایی تقدم را تعیین نمی‌کند.'),
 (47,'Op een rotonde volg je de borden en geef je voorrang volgens de haaientanden.','در میدان تابلوها و دندان‌های کوسه را رعایت کنید.','Nader de rotonde langzaam, geef richting bij verlaten en let op fietsers op de rotonde.','آهسته به میدان نزدیک شوید، هنگام خروج راهنما بزنید و مراقب دوچرخه‌سواران باشید.','Kies de juiste rijstrook vóór je de rotonde oprijdt.','پیش از ورود به میدان خط مناسب را انتخاب کنید.','Wat doe je bij het verlaten van een rotonde?','هنگام خروج از میدان چه می‌کنید؟','Richting naar rechts aangeven','راهنمای راست می‌زنید','Groot licht aanzetten','نوربالا روشن می‌کنید','Achteruitrijden','دنده‌عقب می‌گیرید',0,'Geef richting naar rechts bij het verlaten van de rotonde.','هنگام خروج از میدان راهنمای راست بزنید.'),
 (48,'Fietsers volgen de voorrangstekens, maar zijn bij afslaan beschermd als ze rechtdoor gaan.','دوچرخه‌سواران تابلوهای تقدم را رعایت می‌کنند و هنگام پیچیدن در حرکت مستقیم حمایت می‌شوند.','Controleer fietspaden en geef fietsers voorrang wanneer de regels of hun rechtdoorgang dat vereisen.','مسیرهای دوچرخه را بررسی کنید و هرجا مقررات یا حرکت مستقیمشان لازم می‌کند تقدم دهید.','Kijk naast en achter je vóór je een fietspad kruist.','پیش از قطع مسیر دوچرخه کنار و پشت سر را نگاه کنید.','Waar moet je extra op letten bij een kruispunt met fietsers?','در تقاطع با دوچرخه‌سواران به چه چیز توجه می‌کنید؟','Op hun voorrang en je dode hoek','به تقدم و نقطه کور آن‌ها','Alleen op auto’s','فقط خودروها','Alleen op verkeersborden boven de weg','فقط تابلوهای بالای راه',0,'Fietsers kunnen naast je rijden en vallen gemakkelijk in de dode hoek.','دوچرخه‌سواران می‌توانند کنار شما باشند و در نقطه کور قرار گیرند.'),
 (49,'Geef voetgangers voorrang waar een zebrapad of afsla-regel dat voorschrijft.','هرجا خط عابر یا قاعده پیچیدن الزام کند به عابران تقدم دهید.','Bij afslaan laat je voetgangers die de weg oversteken voorgaan; nader een zebrapad langzaam.','هنگام پیچیدن به عابری که راه را قطع می‌کند راه دهید و آهسته به خط عابر نزدیک شوید.','Controleer ook de oversteek aan de andere kant van de weg.','عبور آن سوی راه را نیز بررسی کنید.','Wie moet je bij afslaan vaak voor laten gaan?','هنگام پیچیدن معمولاً به چه کسی باید راه داد؟','Voetgangers die oversteken','عابران در حال عبور','Alleen bussen','فقط اتوبوس‌ها','Niemand','هیچ‌کس',0,'Afslaand verkeer moet overstekende voetgangers voor laten gaan.','ترافیکِ در حال پیچیدن باید به عابران در حال عبور راه بدهد.'),
 (50,'Botsingsgevaar voorkom je door snelheid te minderen en een uitweg vrij te houden.','با کم کردن سرعت و باز گذاشتن راه فرار از خطر تصادف جلوگیری می‌کنید.','Bij slecht zicht of een onoverzichtelijk kruispunt rijd je zo langzaam dat je kunt stoppen.','در دید کم یا تقاطع نامشخص آن‌قدر آهسته بروید که بتوانید بایستید.','Kijk, denk en handel; neem geen voorrang als je de situatie niet zeker weet.','ببینید، فکر کنید و عمل کنید؛ اگر مطمئن نیستید تقدم را نگیرید.','Wat is de veiligste reactie bij dreigend botsingsgevaar?','در خطر قریب‌الوقوع تصادف ایمن‌ترین واکنش چیست؟','Snelheid minderen en kunnen stoppen','کم کردن سرعت و توانایی توقف','Harder optrekken','شتاب بیشتر','Ogen sluiten en doorrijden','بستن چشم و ادامه دادن',0,'Snelheid minderen geeft tijd en ruimte om een botsing te voorkomen.','کم کردن سرعت زمان و فضا برای جلوگیری از تصادف می‌دهد.')
),release AS (SELECT id FROM content_releases WHERE version=1)
UPDATE course_lessons lesson SET summary=jsonb_build_object('nl',data.summary_nl,'fa',data.summary_fa),content_blocks=jsonb_build_array(jsonb_build_object('type','rule','text',jsonb_build_object('nl',data.rule_nl,'fa',data.rule_fa)),jsonb_build_object('type','exam_tip','text',jsonb_build_object('nl',data.tip_nl,'fa',data.tip_fa)),jsonb_build_object('type','quiz','question',jsonb_build_object('nl',data.question_nl,'fa',data.question_fa),'options',jsonb_build_array(jsonb_build_object('nl',data.option_1_nl,'fa',data.option_1_fa),jsonb_build_object('nl',data.option_2_nl,'fa',data.option_2_fa),jsonb_build_object('nl',data.option_3_nl,'fa',data.option_3_fa)),'correctOption',data.correct_option,'explanation',jsonb_build_object('nl',data.explanation_nl,'fa',data.explanation_fa))),updated_at=NOW() FROM data,release WHERE lesson.release_id=release.id AND lesson.lesson_number=data.lesson_number;
DO $check$ DECLARE n integer; BEGIN SELECT count(*) INTO n FROM course_lessons WHERE release_id=(SELECT id FROM content_releases WHERE version=1) AND lesson_number BETWEEN 41 AND 50 AND content_blocks->2->>'type'='quiz'; IF n<>10 THEN RAISE EXCEPTION 'Intersection lessons validation failed: %',n; END IF; END $check$;
INSERT INTO schema_migrations(version,name) VALUES(13,'intersections_lessons') ON CONFLICT(version) DO NOTHING;
COMMIT;

