-- Complete lessons 61-70 with bilingual overtaking rules and unique quizzes.
BEGIN;
DO $do$
DECLARE i int; nums int[] := ARRAY[61,62,63,64,65,66,67,68,69,70];
 qnl text[] := ARRAY['Wanneer mag je links inhalen?','Welke kant gebruik je normaal om in te halen?','Wat betekent een inhaalverbod?','Wat betekent een doorgetrokken streep?','Waarom is inhalen bij een kruispunt vaak onveilig?','Welke zijafstand houd je bij het inhalen van een fietser?','Wat is belangrijk bij het inhalen van een landbouwvoertuig?','Waarom houd je extra zijafstand?','Wat doe je na het inhalen?','Wanneer haal je zeker niet in?'];
 qfa text[] := ARRAY['چه زمانی می‌توان از چپ سبقت گرفت؟','معمولاً از کدام طرف سبقت می‌گیرید؟','ممنوعیت سبقت یعنی چه؟','خط پیوسته چه معنایی دارد؟','چرا سبقت در تقاطع اغلب ناامن است؟','هنگام سبقت از دوچرخه‌سوار چه فاصله‌ای می‌گیرید؟','هنگام سبقت از وسیله کشاورزی چه مهم است؟','چرا فاصله جانبی بیشتر می‌گیرید؟','پس از سبقت چه می‌کنید؟','چه زمانی حتماً سبقت نمی‌گیرید؟'];
 opts text[][] := ARRAY[
  ARRAY['Als het veilig en toegestaan is','Nooit','Alleen op de vluchtstrook'],ARRAY['Links','Rechts','Over de stoep'],ARRAY['Je mag niet inhalen','Je moet versnellen','Je moet parkeren'],ARRAY['Je mag de streep niet overschrijden','Je moet erover rijden','Het is een fietsstrook'],ARRAY['Je zicht en uitweg zijn beperkt','Het is altijd verplicht','De weg wordt breder'],ARRAY['Minimaal 1 meter','Zo dicht mogelijk','Geen afstand'],ARRAY['Grootte en snelheid inschatten','Claxonneren en blind passeren','Altijd rechts blijven'],ARRAY['Om botsing en schrikreacties te voorkomen','Om sneller te rijden','Om te parkeren'],ARRAY['Veilig terugkeren naar de rechterrijstrook','Links blijven rijden','Remmen op de rijbaan'],ARRAY['Bij onvoldoende zicht of ruimte','Als je haast hebt','Bij groen licht altijd']];
 optsfa text[][] := ARRAY[
  ARRAY['اگر ایمن و مجاز باشد','هرگز','فقط شانه اضطراری'],ARRAY['چپ','راست','روی پیاده‌رو'],ARRAY['نباید سبقت بگیرید','باید شتاب بگیرید','باید پارک کنید'],ARRAY['نباید از خط عبور کنید','باید از روی آن بروید','مسیر دوچرخه است'],ARRAY['دید و راه فرار محدود است','همیشه اجباری است','راه عریض‌تر می‌شود'],ARRAY['حداقل ۱ متر','تا حد ممکن نزدیک','بدون فاصله'],ARRAY['اندازه و سرعت را بسنجید','بوق بزنید و کورکورانه عبور کنید','همیشه راست بمانید'],ARRAY['برای جلوگیری از برخورد و ترس','برای سریع‌تر رفتن','برای پارک'],ARRAY['ایمن به خط راست برگردید','در چپ بمانید','در خط ترمز کنید'],ARRAY['با دید یا فضای ناکافی','وقتی عجله دارید','همیشه با چراغ سبز']];
 rule text[] := ARRAY['Haal alleen links in als je voldoende zicht, ruimte en tijd hebt.','In Nederland haal je normaal links in en keer je daarna veilig terug.','Volg een inhaalverbod; het geldt voor de aangegeven rijrichting.','Een doorgetrokken streep mag je niet overschrijden om in te halen.','Bij kruispunten kunnen onverwachte richtingen en beperkt zicht botsingen veroorzaken.','Houd bij fietsers ruim zijafstand en pas je snelheid aan.','Landbouwvoertuigen zijn breed, langzaam en kunnen onverwacht afslaan.','Extra zijafstand geeft ruimte voor wind, slingeren en onverwachte bewegingen.','Na het inhalen ga je zo snel mogelijk veilig terug naar rechts.','Bij onvoldoende zicht, ruimte of een onduidelijke situatie wacht je.'];
 rulefa text[] := ARRAY['فقط وقتی از چپ سبقت بگیرید که دید، فضا و زمان کافی دارید.','در هلند معمولاً از چپ سبقت می‌گیرید و ایمن به راست برمی‌گردید.','ممنوعیت سبقت را در جهت مشخص‌شده رعایت کنید.','برای سبقت نباید از خط پیوسته عبور کنید.','در تقاطع جهت‌های غیرمنتظره و دید محدود خطر برخورد دارند.','کنار دوچرخه‌سوار فاصله جانبی زیاد و سرعت مناسب بگیرید.','وسایل کشاورزی پهن و کند هستند و ممکن است ناگهانی بپیچند.','فاصله بیشتر برای باد، نوسان و حرکت ناگهانی جا می‌دهد.','پس از سبقت در اولین فرصت ایمن به راست برگردید.','با دید، فضا یا وضعیت نامشخص صبر کنید.'];
 tip text[] := ARRAY['Twijfel je? Dan haal je niet in.','Controleer spiegel en dode hoek vóór teruggaan.','Een verbodsbord gaat vóór je eigen inschatting.','Een onderbroken deel kan inhalen toestaan; de doorgetrokken lijn niet.','Nader elk kruispunt met aangepaste snelheid.','Maak de manoeuvre kort maar geef de fietser veel ruimte.','Let op richtingaanwijzers en grote uitstekende delen.','Zijwind en snelheid vergroten het risico.','Snijd de ander niet af bij het terugkeren.','Veiligheid gaat vóór tijdwinst.'];
 tipfa text[] := ARRAY['اگر شک دارید، سبقت نگیرید.','پیش از برگشت آینه و نقطه کور را بررسی کنید.','تابلوی ممنوعیت بر تشخیص شخصی مقدم است.','بخش منقطع ممکن است اجازه دهد؛ خط پیوسته نه.','با سرعت مناسب به هر تقاطع نزدیک شوید.','مانور را کوتاه انجام دهید اما فضای زیادی بدهید.','راهنما و قسمت‌های بیرون‌زده را بررسی کنید.','باد جانبی و سرعت خطر را بیشتر می‌کند.','هنگام برگشت راه دیگری را نبندید.','ایمنی بر صرفه‌جویی زمان مقدم است.'];
BEGIN
 FOR i IN 1..10 LOOP
  UPDATE course_lessons l SET summary=jsonb_build_object('nl',rule[i],'fa',rulefa[i]),content_blocks=jsonb_build_array(jsonb_build_object('type','rule','text',jsonb_build_object('nl',rule[i],'fa',rulefa[i])) ,jsonb_build_object('type','exam_tip','text',jsonb_build_object('nl',tip[i],'fa',tipfa[i])) ,jsonb_build_object('type','quiz','question',jsonb_build_object('nl',qnl[i],'fa',qfa[i]),'options',jsonb_build_array(jsonb_build_object('nl',opts[i][1],'fa',optsfa[i][1]),jsonb_build_object('nl',opts[i][2],'fa',optsfa[i][2]),jsonb_build_object('nl',opts[i][3],'fa',optsfa[i][3])),'correctOption',0,'explanation',jsonb_build_object('nl',rule[i],'fa',rulefa[i]))),updated_at=NOW() WHERE l.release_id=(SELECT id FROM content_releases WHERE version=1) AND l.lesson_number=nums[i];
 END LOOP;
END $do$;
INSERT INTO schema_migrations(version,name) VALUES(14,'overtaking_lessons') ON CONFLICT(version) DO NOTHING;
COMMIT;

