-- Complete lessons 71-80 with bilingual parking and stopping rules.
BEGIN;
DO $do$
DECLARE i int; nums int[]:=ARRAY[71,72,73,74,75,76,77,78,79,80];
 titles text[]:=ARRAY['Parkeren','Stilstaanverbod','Parkeren bij kruispunt','Parkeren bij zebrapad','Parkeren bij bushalte','Parkeren op stoep','Blauwe zone','Gehandicaptenplaats','Laden en lossen','Veilig uitstappen'];
 rules text[]:=ARRAY['Parkeer alleen waar het is toegestaan en veilig is.','Bij een stilstaanverbod mag je niet stoppen op de rijbaan.','Houd voldoende afstand van een kruispunt zodat zicht en doorgang vrij blijven.','Parkeer niet op of vlak vóór een zebrapad.','Houd de halte en de naderingsruimte voor een bus vrij.','Parkeren op de stoep is verboden tenzij een bord het uitdrukkelijk toestaat.','In een blauwe zone gebruik je een geldige parkeerschijf volgens de aangegeven tijden.','Parkeer op een gehandicaptenplaats alleen met de vereiste gehandicaptenparkeerkaart.','Laden en lossen mag alleen zolang je daadwerkelijk goederen laadt of lost.','Kijk vóór het openen van een portier in de spiegel en over je schouder.'];
 rulesfa text[]:=ARRAY['فقط جایی پارک کنید که مجاز و ایمن باشد.','در ممنوعیت توقف نباید در سواره‌رو توقف کنید.','از تقاطع فاصله کافی بگیرید تا دید و عبور آزاد بماند.','روی خط عابر یا درست پیش از آن پارک نکنید.','ایستگاه و فضای نزدیک شدن اتوبوس را آزاد بگذارید.','پارک روی پیاده‌رو ممنوع است مگر تابلو صریحاً اجازه دهد.','در منطقه آبی طبق زمان‌های تابلو از دیسک معتبر پارک استفاده کنید.','در جای معلولان فقط با کارت معتبر پارک معلولان پارک کنید.','بارگیری و تخلیه فقط هنگام انجام واقعی آن مجاز است.','پیش از باز کردن در آینه و نقطه کور را بررسی کنید.'];
 q text[]:=ARRAY['Waar mag je parkeren?','Wat doe je bij een stilstaanverbod?','Waarom houd je afstand van een kruispunt?','Mag je op een zebrapad parkeren?','Wat moet bij een bushalte vrij blijven?','Mag je op de stoep parkeren?','Wat heb je nodig in een blauwe zone?','Wie mag op een gehandicaptenplaats parkeren?','Wanneer mag je bij laden en lossen blijven staan?','Wat controleer je vóór uitstappen?'];
 qfa text[]:=ARRAY['کجا می‌توانید پارک کنید؟','در ممنوعیت توقف چه می‌کنید؟','چرا از تقاطع فاصله می‌گیرید؟','آیا روی خط عابر می‌توان پارک کرد؟','چه چیزی باید برای اتوبوس آزاد بماند؟','آیا پارک روی پیاده‌رو مجاز است؟','در منطقه آبی چه لازم دارید؟','چه کسی می‌تواند جای معلولان پارک کند؟','هنگام بارگیری چه زمانی می‌توانید بمانید؟','پیش از پیاده شدن چه بررسی می‌کنید؟'];
 opts text[]:=ARRAY['Waar het toegestaan en veilig is','Midden op de rijbaan','Op een zebrapad','Niet stoppen of parkeren','Toch stoppen','Alleen claxonneren','Voor goed zicht en doorgang','Om de auto te wassen','Alleen voor voetgangers','Nee, tenzij een bord het toestaat','Altijd ja','Alleen s avonds','Een parkeerschijf','Een helm','Een tolvignet','Met de vereiste kaart','Iedere bestuurder','Alleen bussen','Zolang je werkelijk laadt of lost','De hele dag','Nooit','Spiegels en dode hoek','Alleen de radio','Alleen de gordel'];
 optsfa text[]:=ARRAY['جایی که مجاز و ایمن است','وسط سواره‌رو','روی خط عابر','توقف یا پارک نکنید','با این حال توقف کنید','فقط بوق بزنید','برای دید و عبور خوب','برای شستن خودرو','فقط برای عابران','خیر، مگر تابلو اجازه دهد','همیشه بله','فقط شب‌ها','دیسک پارک','کلاه ایمنی','برچسب عوارض','با کارت معتبر لازم','هر راننده','فقط اتوبوس‌ها','تا زمانی که واقعاً بارگیری می‌کنید','تمام روز','هرگز','آینه و نقطه کور','فقط رادیو','فقط کمربند'];
BEGIN
 FOR i IN 1..10 LOOP
  UPDATE course_lessons l SET summary=jsonb_build_object('nl',rules[i],'fa',rulesfa[i]),content_blocks=jsonb_build_array(jsonb_build_object('type','rule','text',jsonb_build_object('nl',rules[i],'fa',rulesfa[i])),jsonb_build_object('type','exam_tip','text',jsonb_build_object('nl','Controleer altijd borden en tijden voordat je de auto achterlaat.','fa','پیش از ترک خودرو همیشه تابلوها و زمان‌ها را بررسی کنید.')),jsonb_build_object('type','quiz','question',jsonb_build_object('nl',q[i],'fa',qfa[i]),'options',jsonb_build_array(jsonb_build_object('nl',opts[(i-1)*3+1],'fa',optsfa[(i-1)*3+1]),jsonb_build_object('nl',opts[(i-1)*3+2],'fa',optsfa[(i-1)*3+2]),jsonb_build_object('nl',opts[(i-1)*3+3],'fa',optsfa[(i-1)*3+3])),'correctOption',0,'explanation',jsonb_build_object('nl',rules[i],'fa',rulesfa[i]))),updated_at=NOW() WHERE l.release_id=(SELECT id FROM content_releases WHERE version=1) AND l.lesson_number=nums[i];
 END LOOP;
END $do$;
INSERT INTO schema_migrations(version,name) VALUES(15,'parking_lessons') ON CONFLICT(version) DO NOTHING;
COMMIT;

